name: ci

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    defaults:
      run:
        working-directory: disk-scout
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo generate-lockfile
      - run: cargo test --locked
      - run: cargo build --release --locked
      - if: ${{ matrix.os == 'windows-latest' }}
        run: cargo build --release --locked --features gui --bin disk-scout-gui
